<div class="left-offcanvas">
    <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions"
            aria-controls="offcanvasWithBothOptions" data-mage-init='{"js/offcanvas": {}}'>
        <svg class="bi" width="24" height="24" aria-hidden="true"><use xlink:href="#hamburger"></use></svg>
    </button>
    <div class="offcanvas offcanvas-bottom" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel"></h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close">
                <svg class="bi" width="24" height="24" aria-hidden="true"><use xlink:href="#plus"></use></svg>
            </button>
        </div>
        <div class="offcanvas-body">
            <p>Try scrolling the rest of the page to see this option in action.</p>
        </div>
    </div>
</div>

<div>
    <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithRightSide"
            aria-controls="offcanvasWithBothOptions" data-mage-init='{"js/offcanvas": {}}'>Enable right Offcanvas
    </button>
    <div class="offcanvas offcanvas-end" data-bs-scroll="true" tabindex="-1" id="offcanvasWithRightSide" aria-labelledby="offcanvasWithBothOptionsLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel"></h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close">
                <svg class="bi" width="24" height="24" aria-hidden="true">
                    <use xlink:href="#plus"></use>
                </svg>
            </button>
        </div>
        <div class="offcanvas-body">
            <p>Try scrolling the rest of the page to see this option in action.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam enim nihil omnis aliquam suscipit voluptatem fugit, voluptatum ratione officiis, ut repellat! Quia minus similique accusantium, eum neque tempora aspernatur!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam enim nihil omnis aliquam suscipit voluptatem fugit, voluptatum ratione officiis, ut repellat! Quia minus similique accusantium, eum neque tempora aspernatur!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam enim nihil omnis aliquam suscipit voluptatem fugit, voluptatum ratione officiis, ut repellat! Quia minus similique accusantium, eum neque tempora aspernatur!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam enim nihil omnis aliquam suscipit voluptatem fugit, voluptatum ratione officiis, ut repellat! Quia minus similique accusantium, eum neque tempora aspernatur!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam enim nihil omnis aliquam suscipit voluptatem fugit, voluptatum ratione officiis, ut repellat! Quia minus similique accusantium, eum neque tempora aspernatur!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam enim nihil omnis aliquam suscipit voluptatem fugit, voluptatum ratione officiis, ut repellat! Quia minus similique accusantium, eum neque tempora aspernatur!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam enim nihil omnis aliquam suscipit voluptatem fugit, voluptatum ratione officiis, ut repellat! Quia minus similique accusantium, eum neque tempora aspernatur!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam enim nihil omnis aliquam suscipit voluptatem fugit, voluptatum ratione officiis, ut repellat! Quia minus similique accusantium, eum neque tempora aspernatur!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam enim nihil omnis aliquam suscipit voluptatem fugit, voluptatum ratione officiis, ut repellat! Quia minus similique accusantium, eum neque tempora aspernatur!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam enim nihil omnis aliquam suscipit voluptatem fugit, voluptatum ratione officiis, ut repellat! Quia minus similique accusantium, eum neque tempora aspernatur!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam enim nihil omnis aliquam suscipit voluptatem fugit, voluptatum ratione officiis, ut repellat! Quia minus similique accusantium, eum neque tempora aspernatur!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam enim nihil omnis aliquam suscipit voluptatem fugit, voluptatum ratione officiis, ut repellat! Quia minus similique accusantium, eum neque tempora aspernatur!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam enim nihil omnis aliquam suscipit voluptatem fugit, voluptatum ratione officiis, ut repellat! Quia minus similique accusantium, eum neque tempora aspernatur!</p>

        </div>
    </div>
</div>

<script>
    // require([
    //     'offcanvas'
    // ], function ($) {
    //
    // });
</script>